### PR TITLE
Add information about email action field.

### PR DESCRIPTION
**Pull request by jaimebecker**

### CODE REVIEW

**Review by daccetta2 — CHANGES_REQUESTED** [review]
Jaime - I don't think the viewer screenshot will work because it is not in the correct format. Normally, media has to be linked to the media folder

Here is an example:

**Comment by jaimebecker** [comment]
I didn't change anything about the viewer screenshot - that was there before my changes!

**Comment by peterhallerREL** [comment]
This is the wrong location for where this should be added. It should have been added to the "Fields" page. See my PR for this fix. Please reach out to the PM team if you are unsure where to properly add documentation.

https://github.com/relativitydev/relativity-trace-documentation/pull/350

**Comment by jaimebecker** [comment]
Okay I understand - but so you know, I did reach out to the PM team and this is where we thought to put it.

**Pull request closed without merging**
